name: 'Build V Project'
description: 'GitHub action that builds a vlang project'
author: 'nzbr'
inputs:
  version:
    description: 'Version (latest, version number, weekly, commit ID) of the V compiler to use'
    required: false
    default: 'latest'
branding:
  color: 'blue'
  icon: 'package'
runs:
  using: 'docker'
  image: 'Dockerfile'
